apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kvrocks-standalone.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "kvrocks-standalone.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  kvrocks.conf: |
    bind {{ .Values.kvrocks.bind }}
    port {{ .Values.kvrocks.port }}
    dir {{ .Values.kvrocks.dir }}
    log-level {{ .Values.kvrocks.logLevel }}
