{{- if or (eq .Values.mode "replication") (eq .Values.mode "sentinel") }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kvrocks-standalone.fullname" . }}-replica
spec:
  serviceName: {{ include "kvrocks-standalone.fullname" . }}-replica
  replicas: {{ .Values.replication.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kvrocks-standalone.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/role: replica
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "kvrocks-standalone.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/role: replica
    spec:
      containers:
        - name: kvrocks
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - kvrocks
          args:
            - -c
            - /etc/kvrocks/kvrocks.conf
          ports:
            - name: kvrocks
              containerPort: {{ .Values.kvrocks.port }}
          volumeMounts:
            - name: config
              mountPath: /etc/kvrocks
            - name: data
              mountPath: {{ .Values.kvrocks.dir }}
      volumes:
        - name: config
          configMap:
            name: {{ include "kvrocks-standalone.fullname" . }}-replica-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        {{- if .Values.persistence.storageClassName }}
        storageClassName: {{ .Values.persistence.storageClassName }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
{{- end }}
