apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kvrocks-standalone.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kvrocks-standalone.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  serviceName: {{ include "kvrocks-standalone.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kvrocks-standalone.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "kvrocks-standalone.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: kvrocks
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - kvrocks
          args:
            - -c
            - /etc/kvrocks/kvrocks.conf
          ports:
            - name: kvrocks
              containerPort: {{ .Values.kvrocks.port }}
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/kvrocks
            - name: data
              mountPath: {{ .Values.kvrocks.dir }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "kvrocks-standalone.fullname" . }}-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        {{- if .Values.persistence.storageClassName }}
        storageClassName: {{ .Values.persistence.storageClassName }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
